### ISSUE TITLE
Add section Speakers

### ISSUE THREAD

**Issue by OleksiyRudenko** [inputconf/Input-site#102]
Each speaker card must contain:
- Photo
- Name and Surname
- position
- company/community

Card (or speaker's name if this is better from UX point of view) is linked to a speaker's profile (`target="_blank"`) in facebook.

When fb profile is not available then fallback options are:
- twitter profile
- telegram profile
- none (no linking)

Content source will follow.

**Comment by OleksiyRudenko** [comment]
Each name is linked to a content source. Please, use the name from the relevant source.

[Darya Shvydka](https://docs.google.com/spreadsheets/d/1ONzSCAlIi1sfL5fN0W9Cg3odoLo4DPYHAbHoCQaECdE/edit#gid=1905546511&range=4:4)

[Dima Lylyk](https://docs.google.com/spreadsheets/d/1ONzSCAlIi1sfL5fN0W9Cg3odoLo4DPYHAbHoCQaECdE/edit#gid=1905546511&range=16:16)

[Evegnia Shurupova](https://docs.google.com/spreadsheets/d/1ONzSCAlIi1sfL5fN0W9Cg3odoLo4DPYHAbHoCQaECdE/edit#gid=1905546511&range=9:9)

[Oleksandr Mikhnenko](https://docs.google.com/spreadsheets/d/1ONzSCAlIi1sfL5fN0W9Cg3odoLo4DPYHAbHoCQaECdE/edit#gid=1905546511&range=17:17)

@A-Ostrovnyy , please, take into development

**Comment by A-Ostrovnyy** [comment]
Partially closed by [PR#106](https://github.com/inputconf/Input-site/pull/106)

**Comment by OleksiyRudenko** [comment]
[Ivan Titarenko](https://docs.google.com/spreadsheets/d/1YVnGa2xS3EL3fe3jqPYwsgVW1h-gJG3zqlV8yl7g3MM/edit#gid=1067118097&range=3:3)

[Alex Lapshyn](https://docs.google.com/spreadsheets/d/1YVnGa2xS3EL3fe3jqPYwsgVW1h-gJG3zqlV8yl7g3MM/edit#gid=1067118097&range=7:7)

[Natalia Ilchenko](https://docs.google.com/spreadsheets/d/1YVnGa2xS3EL3fe3jqPYwsgVW1h-gJG3zqlV8yl7g3MM/edit#gid=1067118097&range=8:8)

[Andrey Listochkin](https://docs.google.com/spreadsheets/d/1YVnGa2xS3EL3fe3jqPYwsgVW1h-gJG3zqlV8yl7g3MM/edit#gid=1067118097&range=4:4)

[Piotr Gryko](https://docs.google.com/spreadsheets/d/1YVnGa2xS3EL3fe3jqPYwsgVW1h-gJG3zqlV8yl7g3MM/edit#gid=1067118097&range=5:5)

[Alex Ivanov](https://docs.google.com/spreadsheets/d/1ONzSCAlIi1sfL5fN0W9Cg3odoLo4DPYHAbHoCQaECdE/edit#gid=1905546511&range=2:2)

@A-Ostrovnyy , please, take into development.

**Comment by A-Ostrovnyy** [comment]
Partially closed by [PR#110](https://github.com/inputconf/Input-site/pull/110)

**Comment by OleksiyRudenko** [comment]
[Anna Danovska](https://docs.google.com/spreadsheets/d/1ONzSCAlIi1sfL5fN0W9Cg3odoLo4DPYHAbHoCQaECdE/edit#gid=1905546511&range=14:14)

[Kate Sharlay](https://docs.google.com/spreadsheets/d/1ONzSCAlIi1sfL5fN0W9Cg3odoLo4DPYHAbHoCQaECdE/edit#gid=1905546511&range=13:13)

[Alina Shepsheley](https://docs.google.com/spreadsheets/d/1ONzSCAlIi1sfL5fN0W9Cg3odoLo4DPYHAbHoCQaECdE/edit#gid=1905546511&range=26:26)

[Artem Sychov](https://docs.google.com/spreadsheets/d/1ONzSCAlIi1sfL5fN0W9Cg3odoLo4DPYHAbHoCQaECdE/edit#gid=1905546511&range=11:11)

[Oksana Mykolenko](https://docs.google.com/spreadsheets/d/1ONzSCAlIi1sfL5fN0W9Cg3odoLo4DPYHAbHoCQaECdE/edit#gid=1905546511&range=28:28)

[Andrey Andriyko](https://docs.google.com/spreadsheets/d/1ONzSCAlIi1sfL5fN0W9Cg3odoLo4DPYHAbHoCQaECdE/edit#gid=1905546511&range=10:10)

[Khrystyna Landvytovych](https://docs.google.com/spreadsheets/d/1ONzSCAlIi1sfL5fN0W9Cg3odoLo4DPYHAbHoCQaECdE/edit#gid=1905546511&range=29:29)

[Oleksiy Rudenko](https://docs.google.com/spreadsheets/d/1ONzSCAlIi1sfL5fN0W9Cg3odoLo4DPYHAbHoCQaECdE/edit#gid=1905546511&range=19:19)

@A-Ostrovnyy , please, take into development

**Comment by A-Ostrovnyy** [comment]
Partially closed by [PR#115](https://github.com/inputconf/Input-site/pull/115)

**Comment by A-Ostrovnyy** [comment]
@OleksiyRudenko This is all speakers?
Can we close this issue?

**Comment by OleksiyRudenko** [comment]
@A-Ostrovnyy Not yet. Still need to add a couple

**Comment by OleksiyRudenko** [comment]
1st in the list: [Vladyslava Zatharynna](https://docs.google.com/spreadsheets/d/1ONzSCAlIi1sfL5fN0W9Cg3odoLo4DPYHAbHoCQaECdE/edit#gid=1905546511&range=27:27)

2nd in the list: [Maria Zarudnieva](https://docs.google.com/spreadsheets/d/1ONzSCAlIi1sfL5fN0W9Cg3odoLo4DPYHAbHoCQaECdE/edit#gid=1905546511&range=30:30)

Before Piotr Gryko: [Denys Dovhan](https://docs.google.com/spreadsheets/d/1ONzSCAlIi1sfL5fN0W9Cg3odoLo4DPYHAbHoCQaECdE/edit#gid=1905546511&range=12:12)

Before Andriy Andriyko: [Maksym Tkachuk](https://docs.google.com/spreadsheets/d/1ONzSCAlIi1sfL5fN0W9Cg3odoLo4DPYHAbHoCQaECdE/edit#gid=1905546511&range=15:15)

The following should come before Oleksiy Rudenko:

[Serhiy Koshman](https://docs.google.com/spreadsheets/d/1ONzSCAlIi1sfL5fN0W9Cg3odoLo4DPYHAbHoCQaECdE/edit#gid=1905546511&range=18:18)

[Mykhailo Rudyi](https://docs.google.com/spreadsheets/d/1ONzSCAlIi1sfL5fN0W9Cg3odoLo4DPYHAbHoCQaECdE/edit#gid=1905546511&range=25:25)

[Denys Andrushchenko](https://docs.google.com/spreadsheets/d/1ONzSCAlIi1sfL5fN0W9Cg3odoLo4DPYHAbHoCQaECdE/edit#gid=1905546511&range=24:24)

@A-Ostrovnyy , please, take into development

**Comment by A-Ostrovnyy** [comment]
Partially closed by [PR#135](https://github.com/inputconf/Input-site/pull/135)
