### ISSUE TITLE
Add location address

### ISSUE THREAD

**Issue by OleksiyRudenko** [inputconf/Input-site#104]
Add address beside **Innohub** in the top section:
"Київ, б-р Вацлава Гавела, 6з"

![image](https://user-images.githubusercontent.com/8686631/57697899-f6ba8b00-765c-11e9-9add-2503cb7a0d62.png)

**Comment by A-Ostrovnyy** [comment]
Closed by [PR#105](https://github.com/inputconf/Input-site/pull/105)
@OleksiyRudenko Thank you.
