### ISSUE TITLE
Add partner rabota.ua

### ISSUE THREAD

**Issue by OleksiyRudenko** [inputconf/Input-site#119]
Location: right after DOU

[Source data](https://docs.google.com/spreadsheets/d/1zNqmIPe5H1fceHKaZlVqM_XmDBoJh0k1-nRvK-cXCzU/edit#gid=520866563&range=13:13)
@A-Ostrovnyy , please, take into development.

Update [2019-05-20 15:15]:
Please, make a smaller card for the partner

**Comment by A-Ostrovnyy** [comment]
Closed in [PR#122](https://github.com/inputconf/Input-site/pull/122) by @lenadgit 
@OleksiyRudenko thank you.
