### ISSUE TITLE
Add partner Morshynska

### ISSUE THREAD

**Issue by cuteshaun** [inputconf/Input-site#121]
Location: left, after InnoHub
[Source data](https://docs.google.com/spreadsheets/d/1zNqmIPe5H1fceHKaZlVqM_XmDBoJh0k1-nRvK-cXCzU/edit#gid=520866563)
@A-Ostrovnyy , please, take into development.

**Comment by A-Ostrovnyy** [comment]
Closed in [PR#122](https://github.com/inputconf/Input-site/pull/122) by @lenadgit 
@CuteShaun Thank you.
