### ISSUE TITLE
Replace a speaker

### ISSUE THREAD

**Issue by OleksiyRudenko** [inputconf/Input-site#124]
Replace **Dima Lylyk** with:
Name: **Сергій Фролов**
Image: https://drive.google.com/open?id=1O5eIm7Z0pSzWiuWHPJWyCJmMljasHq0V
Position: **Lead Frontend Engineer**
Company: **rabota.ua**

Unfortunately, Dima had to quit due to force majeure.

**Comment by A-Ostrovnyy** [comment]
Closed by [PR#126](https://github.com/inputconf/Input-site/pull/126)
