### ISSUE TITLE
Add section Inspired by

### ISSUE THREAD

**Issue by OleksiyRudenko** [inputconf/Input-site#125]
Add section after Media partners:
Title: Inspired by (design similar to **Медіа-партнери**)
Card:
- full width card (design similar to Ring or WIX card)
- logo from MediaPartners/ZLIT
- text from MediaPartners/ZLIT tooltip

Remove ZLIT from Media Partners

**Comment by A-Ostrovnyy** [comment]
Closed by [PR#127](https://github.com/inputconf/Input-site/pull/127)
