### ISSUE TITLE
Fix Partner/rabota.ua logo

### ISSUE THREAD

**Issue by OleksiyRudenko** [inputconf/Input-site#129]
The source has red "R" in a red circle (see [logo image](https://drive.google.com/file/d/0By_1gNcMlZs6MXRNdm1nTUh5U3Zfd3ZBeTEwM3E2bjBpbDVF/view) under source in  #119)

Current implementation offers all-black.
Please, fix. Many brands do not allow posting changed and unaligned design. This is the case.

![image](https://user-images.githubusercontent.com/8686631/58091284-e2810b80-7bd1-11e9-917c-b2cc71ce8467.png)

**Comment by OleksiyRudenko** [comment]
Also `rabota.ua` must be all lower case.

**Comment by A-Ostrovnyy** [comment]
Closed in [PR#130](https://github.com/inputconf/Input-site/pull/130) by @lenadgit 
and in [PR#133](https://github.com/inputconf/Input-site/pull/133)
