### ISSUE TITLE
Add Partner/JetBrains

### ISSUE THREAD

**Issue by OleksiyRudenko** [inputconf/Input-site#132]
After media partners:

Name:
Logo: Any of JetBrains main logos here https://www.jetbrains.com/company/brand/logos/
Tooltip: At JetBrains, code is our passion. For over 15 years we have strived to make the strongest, most effective developer tools on earth. By automating routine checks and corrections, our tools speed up production, freeing developers to grow, discover and create.

**Comment by A-Ostrovnyy** [comment]
Closed by [PR#134](https://github.com/inputconf/Input-site/pull/134)
@OleksiyRudenko Thank you!

**Comment by OleksiyRudenko** [comment]
Need to replace logo.
Please, take one from section *JetBrains Logo*

**Comment by A-Ostrovnyy** [comment]
Closed by @lenadgit in [PR#141](https://github.com/inputconf/Input-site/pull/141)
