### ISSUE TITLE
Add Denys Andrushchenko to Topics block

### ISSUE THREAD

**Issue by OleksiyRudenko** [inputconf/Input-site#139]
Add Denys Andrushchenko to Topics block
sections Personal experience (Як я щастя в ІТ шукав Денис Андрущенко (GeekHub, менеджер)) Communities (GeekHub Денис Андрущенко (GeekHub, менеджер))

Sources:
http://input.tilda.ws/programa#experience
http://input.tilda.ws/programa#communities

**Comment by A-Ostrovnyy** [comment]
Closed by @lenadgit in [PR#140](https://github.com/inputconf/Input-site/pull/140)
@OleksiyRudenko thank you.
