### ISSUE TITLE
Headings alignment

### ISSUE THREAD

**Issue by A-Ostrovnyy** [inputconf/Input-site#24]
@denislukianenko on the different viewports headings have different alignment (center or left) can you clarify/fix this issue.
Let me know if you decide to fix it by yourself.

**Comment by denlukia** [comment]
Headings alignments are dictated rather by content postioning, following them, then sticking to one type of alignment. For example: In About section it's better to align heading to the left side of the paragraph after it, but in the next section – "How it will be" – the cards are better to be centered on mobile, so there's no too much empty space on the right (if align them to the left), and section's heading is aligned accordingly

**Comment by denlukia** [comment]
Finalized alignments in #29

**Comment by A-Ostrovnyy** [comment]
Closed by @denislukianenko in [PR#29](https://github.com/inputconf/Input-site/pull/29)
