### ISSUE TITLE
Remove extra white space on the right side on mobile view

### ISSUE THREAD

**Issue by A-Ostrovnyy** [inputconf/Input-site#25]

**Comment by denlukia** [comment]
May you clarify what do you mean?

**Comment by A-Ostrovnyy** [comment]
@denislukianenko [image](https://imgur.com/a/aZB2Pn8)
It because of font-size is too big for mobile view

**Comment by A-Ostrovnyy** [comment]
Closed by @denislukianenko in [PR#31](https://github.com/inputconf/Input-site/pull/31)
