### ISSUE TITLE
[Discuss] Modify "our-team" photo to more art-focused according to medium quality of picture

### ISSUE THREAD

**Issue by IgorKurkov** [inputconf/Input-site#30]
I used [picsart](https://picsart.com) as android app for fast rewriting regular images to something awesome and attracting. there are some examples, you can take a look and discuss about this, I think It can be more interesting and fresh and easy to do. 
![photo_2019-04-17_14-43-51_cr](https://user-images.githubusercontent.com/29090227/56285593-43737a80-6120-11e9-97b7-015d33f7f54f.jpg)
![photo_2019-04-17_14-44-01_cr](https://user-images.githubusercontent.com/29090227/56285594-43737a80-6120-11e9-86a9-c9f55ee98f24.jpg)
![photo_2019-04-17_14-44-06_cr](https://user-images.githubusercontent.com/29090227/56285595-440c1100-6120-11e9-90a6-eea7f1f33e1c.jpg)
![photo_2019-04-17_14-44-12_cr](https://user-images.githubusercontent.com/29090227/56285596-440c1100-6120-11e9-8bb4-6f9b9faa293f.jpg)
![photo_2019-04-17_14-44-16_cr](https://user-images.githubusercontent.com/29090227/56285597-440c1100-6120-11e9-92e9-b571c45b9d4b.jpg)
![photo_2019-04-17_14-44-19_cr](https://user-images.githubusercontent.com/29090227/56285598-440c1100-6120-11e9-8cda-cdd12afa4656.jpg)
![photo_2019-04-17_14-44-23_cr](https://user-images.githubusercontent.com/29090227/56285599-440c1100-6120-11e9-830b-fcdb8bf45f1e.jpg)
![photo_2019-04-17_14-44-27_cr](https://user-images.githubusercontent.com/29090227/56285600-44a4a780-6120-11e9-8f00-f79657d72ceb.jpg)
![photo_2019-04-17_14-45-25_cr](https://user-images.githubusercontent.com/29090227/56285601-44a4a780-6120-11e9-8346-7e6e7baa3776.jpg)

there are dozens of variants in picsart, I provide only a few variants.

**Comment by A-Ostrovnyy** [comment]
@denislukianenko @yulyasystem

**Comment by denlukia** [comment]
@IgorKurkov If the quality is the main concern, I can replace current 1440x908 (348KB) picture for 4375 x 2838 (870KB) image

**Comment by OleksiyRudenko** [comment]
@IgorKurkov @A-Ostrovnyy how about lazy load and replace static image with an animated version on load?
https://drive.google.com/open?id=1RihnOdyJxp1YEh9IPjq9RQxDA3AxDXuH

**Comment by IgorKurkov** [comment]
@denislukianenko 870kb have no sense according to long ttfb and downloading time, @OleksiyRudenko gif will be once more bigger than 870kb also. Lazy load can make sense but I mean only medium quality of picture as plenty of photo noise according to bad camera/lights etc. Lazy load will be good idea, some preload/prefetch, but I think bigger size of image nof achieved goal with noiseless problem, so my point was make something with image. But it's not so important, only a things how to make the team photo more swaggy ;)

**Comment by IgorKurkov** [comment]
I saw, now quality is much better. Let's close issue
