### ISSUE TITLE
Add Tickets section

### ISSUE THREAD

**Issue by OleksiyRudenko** [inputconf/Input-site#61]
- Add section as per mock-up: http://input.tilda.ws/tickets
- CTO button must lead to: https://inputconf.2event.com/ ~(not published yet, one click away)~
- top menu bar must contain a link to the section

**Comment by OleksiyRudenko** [comment]
@A-Ostrovnyy can we, please, drive this into production? We have launched the sales.

**Comment by A-Ostrovnyy** [comment]
Closed by [PR#77](https://github.com/inputconf/Input-site/pull/77)
@OleksiyRudenko Thank you.
