### ISSUE TITLE
Add Partners section

### ISSUE THREAD

**Issue by OleksiyRudenko** [inputconf/Input-site#62]
Draft Mock-up: http://input.tilda.ws/partners
(details to be discussed)

Info re partners: https://docs.google.com/spreadsheets/d/1zNqmIPe5H1fceHKaZlVqM_XmDBoJh0k1-nRvK-cXCzU/edit#gid=520866563

[Restricted access]

**Comment by A-Ostrovnyy** [comment]
Closed by [PR#66](https://github.com/inputconf/Input-site/pull/66)
