### ISSUE TITLE
Add subsection Media partners

### ISSUE THREAD

**Issue by OleksiyRudenko** [inputconf/Input-site#73]
Add subsection Media partners in Partners section.
Each item will be a card with:
- partner's small logo
- partner's name
- linked to a given resource
- optional partner's text as a tooltip visible on hover

**Comment by OleksiyRudenko** [comment]
Add **fwdays** to subsection Media partners:
- logo: https://fwdays.com/assets/img/logo_header.svg (remove text)
- name: fwdays
- link: https://fwdays.com/
- tooltip: fwdays проводить якісні заходи для розробників, архітекторів, СТО, тім та тех лідів, менеджерів проектів і всіх, хто пов'язаний з IT

**Comment by alexdefender** [comment]
Add **from-ua.com** to subsection Media partners:

- logo: https://drive.google.com/file/d/1LqpEdt_NSheMsvp9hSaBJOXIKeYQKeVb/view?usp=sharing
- name: From-UA
- link: https://from-ua.com/
- tooltip: Відоме українське інтернет-видання From-UA є одним з найбільш популярних інформаційно-аналітичних і розважальних мережевих ЗМІ України.

**Comment by alexdefender** [comment]
Add prnews.io to subsection Media partners:

- logo: https://drive.google.com/open?id=1yWeb-BXGQV7S8PohPnmDB2xBlJBOiVTo
- name: PRNEWS.IO
- link: https://prnews.io/
- tooltip: PRNEWS.IO є одним з популярних інструментів з управління PR-активністю компанії в інтернеті. Заснована на концепції «все в одному вікні», PRNEWS.IO дозволяє бізнесу створювати і ділитися історіями з журналістами на власних умовах.

**Comment by OleksiyRudenko** [comment]
Add **front_end_dev** to subsection Media partners:

* logo: https://drive.google.com/open?id=1iU2bSWlji_XYuqcz40El94RMS9TP6pAn
* name: front_end_dev
* link: https://t.me/front_end_dev
* tooltip: FrontEndDev - дайджест полезных материалов для front end разработчиков

**Comment by A-Ostrovnyy** [comment]
The first part was closed by [PR#80](https://github.com/inputconf/Input-site/pull/80).
@OleksiyRudenko and @alexdefender Thank you.

**Comment by OleksiyRudenko** [comment]
Add **ZLIT** to subsection Media partners:

logo: https://static.tildacdn.com/tild6636-3731-4362-b961-346636383632/noroot.png
name: ZLIT
link: https://zlit.events/
tooltip: Zlit - это слёт самых активных участников IT-сообществ Киева, это путешествие на темную сторону IT индустрии, это необычно и про люд

**Comment by A-Ostrovnyy** [comment]
ZLIT was added by [PR#82](https://github.com/inputconf/Input-site/pull/82).
@OleksiyRudenko Thank you.

**Comment by alexdefender** [comment]
DRAFT

Add **ЛІГА.net** to subsection Media partners:

- logo: https://drive.google.com/file/d/1Z693_s1PH7nyooSbOqZzhpeWhwf8v1uJ/view?usp=sharing
- name: ЛІГА.net
- link: https://www.liga.net/
- tooltip: ЛІГА.net - незалежний діловий інформаційний портал. На сьогоднішній день ЛІГА.net - один з лідерів за охопленням аудиторії українського Інтернету, займає лідируючі позиції в сегменті новинних і ділових медіа. За даними профільних аудиторів Інституту масової інформації, портал - незмінний лідер за дотриманням журналістських стандартів серед великих українських інтернет-ЗМІ.

**Comment by A-Ostrovnyy** [comment]
ЛІГА.net added by [PR#93](https://github.com/inputconf/Input-site/pull/93)
@alexdefender Thank you.

**Comment by alexdefender** [comment]
Add interfax.com.ua to subsection Media partners:

logo: https://drive.google.com/open?id=1OANpmBAb8CkTCBu2o2GauezT3BlZUyR8
name: Інтерфакс-Україна
link: https://interfax.com.ua
tooltip: "Інтерфакс-Україна" - лідер новин. Оперативно та об'єктивно про головне.

**Comment by A-Ostrovnyy** [comment]
Interfax added by [PR#103 ](https://github.com/inputconf/Input-site/pull/103)
@alexdefender Thank you.

**Comment by A-Ostrovnyy** [comment]
ChernivstiJS added by [PR#131](https://github.com/inputconf/Input-site/pull/131)
