### ISSUE TITLE
Change description for Partners/Star

### ISSUE THREAD

**Issue by OleksiyRudenko** [inputconf/Input-site#81]
Change card text for **Star**

~Star creates an integrated, seamless workflow – no matter how long or complex the client journey'~

Star є global consultancy, яка поєднує ідею, стратегію, дизайн, інженерні та маркетингові практики у безперешкодний робочий процес, розроблений для підтримки наших клієнтів на кожному кроці — незалежно від того, наскільки довгою та складною є їхня подорож

**Comment by A-Ostrovnyy** [comment]
Closed by [PR#83](https://github.com/inputconf/Input-site/pull/83)
@OleksiyRudenko Thank you.
