### ISSUE TITLE
Add sponsors subsection

### ISSUE THREAD

**Issue by zonzujiro** [inputconf/Input-site#84]
Add https://www.wix.com/ to subsection sponsors:

- logo: https://drive.google.com/file/d/17LL16qfd5m58cZvS8LtbeuTsiKTZT9ta/view?usp=sharing
- name: Wix
- link: https://www.wix.com/
- tooltip: Wix Engineering побудували таку платформу, на якій кожен без зусиль може створити вебсайт або веб-додаток. Простота процесу для користувачів драйвить  інженерів постійно посилювати технічну експертизу, знаходити нестандартні рішення і бути на гребені інновацій. Wix активно ділиться власним досвідом на конференціях, а невдовзі розпочне власну серію технічних мітапів. Культура в Wix орієнтована на розробника, де кожному довірено впливати на життя продуктів і нести відповідальність за впровадження нових функцій і їх продуктивність в робочому середовищі.

**Comment by OleksiyRudenko** [comment]
@zonzujiro
A suggestion:
Add to Partners section, right before DOU

Please, confirm

**Comment by zonzujiro** [comment]
@OleksiyRudenko sponsors, who gave money, and media partners in one section? 🤔 

I am not sure. What possible caveats we can receive?

**Comment by OleksiyRudenko** [comment]
@zonzujiro Sponsors are visualized with a  bigger card and some accompanying text

**Comment by A-Ostrovnyy** [comment]
Closed by [PR#85](https://github.com/inputconf/Input-site/pull/85) and [PR#90](https://github.com/inputconf/Input-site/pull/90)
@lenadgit , @zonzujiro , @OleksiyRudenko Thank you.
