### ISSUE TITLE
Add `id` property to items in sections

### ISSUE THREAD

**Issue by OleksiyRudenko** [inputconf/Input-site#86]
It would be great to have `id` property for notable items within sections like partner cards etc.

This way it is possible to make a link e.g. https://inputconf.org/#partner_rails_reactor that will lead directly to a desired item.

**Why?**

To show a partner their card is published. They won't need to scroll and will see the proof of publishing instantly.

@A-Ostrovnyy what do you think?

**Comment by A-Ostrovnyy** [comment]
Cool, @lenadgit working on it.

**Comment by A-Ostrovnyy** [comment]
Closed by [PR#94 ](https://github.com/inputconf/Input-site/pull/94)
@OleksiyRudenko thank you
