### ISSUE TITLE
Change logo for ZLIT

### ISSUE THREAD

**Issue by OleksiyRudenko** [inputconf/Input-site#89]
In section **Partner** subsection **Media partners** card **ZLIT**
change logo (see attachment).

[ZLIT-logo](https://user-images.githubusercontent.com/8686631/57360460-e305b500-7182-11e9-911b-1f45b9ae7c39.png)

![ZLIT-logo](https://user-images.githubusercontent.com/8686631/57360460-e305b500-7182-11e9-911b-1f45b9ae7c39.png)

**Comment by A-Ostrovnyy** [comment]
Closed by [PR#92](https://github.com/inputconf/Input-site/pull/92)
@OleksiyRudenko Thank you.
